language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

env:
  - FLASK_VERSION=1.0.2

before_script:
  - export APP_SECRET_KEY='anythinganythingsecret'
  - psql -c "CREATE DATABASE testing;" -U postgres
  - export APP_SETTINGS=testing
  - export TESTING_DB=test_db
  - export DEV_DB=fast_food_db
  - export DB_HOST=localhost
  - export USER='gloria'
  - export PASSWORD='bubble24'
  - source venv/bin/activate
  - python api/v2/connect_to_db.py

script:
  - python -m pytest

after_success:
  - coveralls

cache: pip
