language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

env:
  - FLASK_VERSION=1.0.2

before_script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
  - python api/v2/connect_to_db.py

script:
  - python -m pytest

after_success:
  - coveralls

cache: pip
